---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: daps
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      daps:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/drazzilb08/daps
              tag: v2.0.3@sha256:946f04c876c492c546bcd1eb7a6686e6011507f3812b3b8a18e56802f4ec9971
            env:
              TZ: Europe/Oslo
            probes:
              liveness: &probes
                enabled: false
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: false
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: daps
        ports:
          http:
            port: &port 8000
    route:
      app:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        existingClaim: daps
      media:
        type: nfs
        server: 192.168.0.3
        path: /volume1/data
        globalMounts:
          - path: /mnt/local
      tmp:
        type: emptyDir
        advancedMounts:
          daps:
            app:
              - path: /config/log
                subPath: log
              - path: /tmp
                subPath: tmp
              - path: /etc/group
                subpath: etc
