---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/common
resources:
  - ./audiobookshelf/ks.yaml
  - ./autobrr/ks.yaml
  - ./bazarr/ks.yaml
  - ./cross-seed/ks.yaml
  - ./daps/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./kometa/ks.yaml
  - ./maintainerr/ks.yaml
  - ./notifiarr/ks.yaml
  - ./plex/ks.yaml
  - ./plex-trakt-sync/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./qui/ks.yaml
  - ./radarr-hd/ks.yaml
  - ./radarr-uhd/ks.yaml
  - ./readarr/ks.yaml
  - ./readarr-ab/ks.yaml
  - ./sonarr-hd/ks.yaml
  - ./sonarr-uhd/ks.yaml
  - ./tautulli/ks.yaml
  - ./tqm/ks.yaml
  - ./unpackerr/ks.yaml
