---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: "${APP}"
spec:
  sourcePVC: "${APP}"
  trigger:
    schedule: "0 6 * * *"
  restic:
    accessModes: ["${VOLSYNC_SNAP_ACCESSMODES:=ReadWriteOnce}"]
    cacheAccessModes: ["${VOLSYNC_CACHE_ACCESSMODES:=ReadWriteOnce}"]
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:=5Gi}"
    cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:=longhorn-cache}"
    copyMethod: "${VOLSYNC_COPYMETHOD:=Snapshot}"
    moverSecurityContext:
      runAsUser: ${VOLSYNC_PUID:=1000}
      runAsGroup: ${VOLSYNC_PGID:=1000}
      fsGroup: ${VOLSYNC_PGID:=1000}
    pruneIntervalDays: 14
    repository: "${APP}-volsync-secret"
    retain:
      hourly: 24
      daily: 14
      monthly: 1
      yearly: 6
    storageClassName: "${VOLSYNC_STORAGECLASS:=longhorn-snapshot}"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:=longhorn}"
