apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-helm-chart-value-overrides
  namespace: kube-system
data:
  values.yaml: |-
    kubeProxyReplacement: true
    ipam:
      mode: kubernetes
    routingMode: tunnel
    tunnelProtocol: vxlan
