apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-helm-chart-value-overrides
  namespace: kube-system
data:
  values.yaml: |-
    kubeProxyReplacement: true
    ipam:
      mode: kubernetes
    routingMode: tunnel
    tunnelProtocol: vxlan
    rollOutCiliumPods: true
    l2announcements:
      enabled: true
    externalIPs:
      enabled: true
    envoy:
      rollOutPods: true
    operator:
      rollOutPods: true
      replicas: 1
    hubble:
      relay:
        rollOutPods: true
      ui:
        rollOutPods: true
    k8sClientRateLimit:
      qps: 50
      burst: 100

