---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app qbittorrent
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      qbittorrent:
        containers:
          app:
            nameOverride: qbittorrent
            image:
              repository: ghcr.io/hotio/qbittorrent
              tag: release-5.1.2
            env:
              PUID: 1000
              PGID: 1000
              TZ: Europe/Oslo
              QBT_TORRENTING_PORT: &torrentPort 50413
              QBT_WEBUI_PORT: &port 8080
            probes:
              liveness: &probes
                enabled: false
                custom: true
                spec:
                  httpGet:
                    path: /api/v2/app/version
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: true
              readOnlyRootFilesystem: false
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 16Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: false
    service:
      app:
        forceRename: *app
        primary: true
        ports:
          http:
            port: *port
      bittorrent:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 192.168.0.249, ::ffff:192.168.0.249
        ports:
          bittorrent-tcp:
            port: *torrentPort
            protocol: TCP
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
          - "qb.${SECRET_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        existingClaim: qbittorrent
        globalMounts:
          - path: /config/config
            subPath: config
          - path: /config/data
            subPath: data
      media:
        type: nfs
        server: 192.168.0.3
        path: /volume1/data
        globalMounts:
          - path: /mnt/local
      tmp:
        type: emptyDir
