# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-user: ENC[AES256_GCM,data:DLYUCw==,iv:uMzXnu+h4cVwYvAL58J4y7StZDtZ3axhl/jc4PCo6mU=,tag:tWU/7DD57QQG096IqhWQPw==,type:str]
    admin-password: ENC[AES256_GCM,data:DtBfMtT/I7uXy3tebjs4JV4fN3fKx7IX,iv:NEe7OQrAidgZzXvJO1kYkApLf/AGOQpUf9+qUdA1qQc=,tag:ttUFs48c7XYmo9WCK55TXA==,type:str]
sops:
    age:
        - recipient: age1qclp6ljen59ktt48l8zudqfdnemuz97kfvnumjv9ay06gzfzuqjs4r9y9r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzV1RwYlZEMU5vTGE1WVAw
            YldYOHMrTTdQTXlLZlJ6YkRrZDRGTkVLOVNJCk1Pb2I4YWZZOW4wd2pnTER3cWRn
            MzM1MUE5ZnVZTFJyWWRwNDArMUI5N00KLS0tIHRZa2xjR0RiR0NET3BpdkZ6WndO
            MFFpU1g3cW5WVDVWUGVWUVNiRU9aZEUKzTLvH8FDzIcX9/XkylGjlzk44ubqi0uc
            57mHF/cMi6FGQakwP2gwdtv3r+P10eI/lLKNoC1Sgyxmu8QPabnRww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-03T09:24:31Z"
    mac: ENC[AES256_GCM,data:udFu9RdJvanExBAq5eRKRRCbqAz/xNO8DHDL4QOr6tFhRYBTFQ5Bng+JhG0dlBo7errJ3C6bcX5EqcYTPzhpaVz2fkWiHbD0vIl2YfIkTAfQSiE3gr92w/dbJ93LZqGUziljXc15yvHsGpmPLE6cY+vLVyWWuMaVla0FmUxwbHM=,iv:wC5D3sfEZJjitUf/YtiH62kL1jPCzxJFt1fhuAS1wg0=,tag:FU+kMtKugmnXqX1Tf00yow==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
