# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
stringData:
  admin-user: ENC[AES256_GCM,data:PQ9LlnPyPCc=,iv:1n7BBkrlN8k4BxKwZQD8XaabFs//fV31zVbog3c1t3Y=,tag:VVc11jnOGKh7CjI5yYM+rg==,type:str]
  admin-password: ENC[AES256_GCM,data:7sXuFT+vMYrn4dxnSOhqzF1sVLZiJekfi6Hvr79vToZWMT8n,iv:9tsVU262wqwMaRWHO0RG1Qi+FO4msILUGxAp/ulTuYg=,tag:57GvnMK8SLHuPHL46oNo8g==,type:str]
sops:
  age:
    - recipient: age1qclp6ljen59ktt48l8zudqfdnemuz97kfvnumjv9ay06gzfzuqjs4r9y9r
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzV1RwYlZEMU5vTGE1WVAw
        YldYOHMrTTdQTXlLZlJ6YkRrZDRGTkVLOVNJCk1Pb2I4YWZZOW4wd2pnTER3cWRn
        MzM1MUE5ZnVZTFJyWWRwNDArMUI5N00KLS0tIHRZa2xjR0RiR0NET3BpdkZ6WndO
        MFFpU1g3cW5WVDVWUGVWUVNiRU9aZEUKzTLvH8FDzIcX9/XkylGjlzk44ubqi0uc
        57mHF/cMi6FGQakwP2gwdtv3r+P10eI/lLKNoC1Sgyxmu8QPabnRww==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-02T17:25:11Z"
  mac: ENC[AES256_GCM,data:Xl5LIKX3InW3hz/k2P0dmpbEr+oq5tL6FKIPH6+FXto5gyHnpEksVB2wIBp16pSO00UXfO5VvL3Uur67NOvZ1+9Fj7TCLMYYMG80bwOzqo8OWnxoYOi01t2gujsBZnXF7Irkq88Nzm2oTwQaV+3D/otJRXjpPFEzfU774Ec9K4A=,iv:HvQa/oh/umyW3RD4Wt9BDq83G5Rzi/EqZNRYv3MJ3M8=,tag:alMcw5lxn/5OmFz6ngG28Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
