{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cloudflare-api-token",
    "namespace": "external-dns",
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cloudflare-api-token",
        "namespace": "external-dns",
      }
    },
    "encryptedData": {
      "cloudflare_api_token": "AgALy/Wen9nx7pZOpM5kGGsWq9c/rbww22bdbTHAQMpzYPNA5OmMEQQs9q8+kFoTHJoHivsxON2KVD7HglCMgsRhOVq8ImpANKowdLLRouGF64NWO4CXvozFDRuQYOKqQU9fjF0Qp75UcA/qpF41wWYFazZmNkDHTRs8+i/Bpa8VNz3J1qqrYcTFSH91vcNkB6hDIVXb5PLU8rwPM73j5byQ92+tva1v8SD1uFYWbadYPmpq89eiP6hxgZWhnhhsn9UmR85kzNjf9KpgXBTTvtg/+uP6h/nDZpGs6qalOWQdghVRZAW5BGdabu0SCVR1v3Cso70lATWJsuqnMaSNcicpPsM9UPCerK6SKGehf8Q8D9vUsyruMQes66pTPcatu/hoDWaxRmjgR5CpXlc7/TtWchLJTZZryf6M6uiVyGJUHKH/WCRccNLy+yGA4JJR/c6UH8pcj2pX7N+D4V8mlP5YWyOVb9MxPWuH+KbzzMt8LefVeLnMATwImJdPDaFoGzsKNoFfGX7DnNC4GK4tot3dCnEkR7GgZSL61He2QzA8rHtN494K+ESUFYz5kqFKr5OL/EfJoK/7KXppADHbUlECEWSy2bKTXB87uHmhCkOCT6A76ZLutXMC3sUT1SRZ1vQxE+H5YaF+wNjX3AsthItPLa0xhozKrxvVSIN5rEDgzpaaJxJseU0j5IVgzQZaQg1uTItyedrH7FwoxnPJXVZ+bkfYN3aPYGhSDucMHsDLrQ61c5/bNYfo"
    }
  }
}
