---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted
components:
  - ../../components/common
resources:
  - ./krisbot/ks.yaml
  - ./lspd-application/ks.yaml
  - ./lspd-application-dev/ks.yaml
  - ./lssd-image-uploader/ks.yaml
  - ./mining-cult/ks.yaml
  - ./n8n/ks.yaml
  - ./thelounge/ks.yaml
