---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kometa
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: kometa-secret
    template:
      data:
        KOMETA_PLEX_API_KEY: "{{ .PLEX_API_KEY }}"
        KOMETA_RADARR_HD_API_KEY: "{{ .RADARR_HD_API_KEY }}"
        KOMETA_RADARR_UHD_API_KEY: "{{ .RADARR_UHD_API_KEY }}"
        KOMETA_SONARR_HD_API_KEY: "{{ .SONARR_HD_API_KEY }}"
        KOMETA_SONARR_UHD_API_KEY: "{{ .SONARR_UHD_API_KEY }}"
        KOMETA_TAUTULLI_API_KEY: "{{ .TAUTULLI_API_KEY }}"
        KOMETA_TMDB_API_KEY: "{{ .TMDB_API_KEY }}"
  dataFrom:
    - extract:
        key: plex
    - extract:
        key: radarr
    - extract:
        key: sonarr
    - extract:
        key: tautulli
    - extract:
        key: tmdb
