# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: unifi-dns-secret
stringData:
    UNIFI_API_KEY: ENC[AES256_GCM,data:YASUACsfK5xNyVrB0vtWVta6XeRdvpMvvZjuHz3Jwi0=,iv:UpXJtjJAhAxbSQkkcGkiEq4gM1Kz9Lef1Fi1RzBSGgg=,tag:4/czn+sQteG/FSEyZ1EBwg==,type:str]
sops:
    age:
        - recipient: age1qclp6ljen59ktt48l8zudqfdnemuz97kfvnumjv9ay06gzfzuqjs4r9y9r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoeEtKSFFvVG1pTk9CQXVK
            c0RNL0loQ21ISWFHTzNnWk9xMlJ3UzdyZXpVCjEwMTJVRUdzR1ZCb3pTbzVWMW1E
            S09MNW5jenNBRXY3QW9CZWxma0tCVlEKLS0tIFdLMURGSjRWaGJBMnNsbjd0dnla
            SkZ2WkJscHFiSzNPZjVYVm8wQW9PN00KoIJEi2FPIBh9skxNBtEtnGmN0m51+caR
            j/aCVGVmUuGvO/9C3TSgxl8o2RGU+KwZwpCu1h4o24pHfzxilc+e5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-12T15:01:45Z"
    mac: ENC[AES256_GCM,data:a5VsLOrVJaIzFBhPtWL7VjZLV2A/6gWz1D05ikH8mvSyqrQzyuT3tQKULl3Y6omDbnxcUVQacNQRD2Bz1+/f8RDbFISI+F8O8RkbD95v7R2GS69Bxa8iNcVLgqOwDaa695vAFeiMWE6sPpL1YTM77LfaPWG+MqW7jpbsow7jQBE=,iv:o4CufCYlaD9uiq0lcoQ+pU9zu1ZrV4qPZJZI00OprTc=,tag:8tDY8MxLwwdktG4YYWEmUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
