# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.0.10:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.0.10"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "talos-01"
    ipAddress: "192.168.0.20"
    installDiskSelector:
      serial: "S4EVNF0M454702F"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/bd28b5ed4b5895ad935cb0e23723ed1e2d2f3fd559eec9f25cdfea3d145e8a9e
    schematic:
      customization:
        extraKernelArgs:
          - -init_on_alloc          # Less security, faster puter
          - -init_on_free           # Less security, faster puter
          - -selinux                # Less security, faster puter
          - apparmor=0              # Less security, faster puter
          - i915.enable_guc=3       # Kaby Lake CPU / iGPU
          - init_on_alloc=0         # Less security, faster puter
          - init_on_free=0          # Less security, faster puter
          - intel_iommu=on          # PCI Passthrough
          - iommu=pt                # PCI Passthrough
          - pcie_aspm=off           # Disable PCIe ASPM
          - mitigations=off         # Less security, faster puter
          - security=none           # Less security, faster puter
          - talos.auditd.disabled=1 # Less security, faster puter
        systemExtensions:
          officialExtensions:
            - siderolabs/i915 # Intel iGPU
            - siderolabs/intel-ucode # Intel iGPU
            - siderolabs/iscsi-tools # Longhorn
            - siderolabs/mei # Intel iGPU
            - siderolabs/util-linux-tools # Longhorn
    controlPlane: true
    userVolumes:
      - name: local-hostpath
        provisioning:
          diskSelector:
            match: disk.serial == "S4J4NX0R819227P"
          maxSize: 2TB
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "54:b2:03:19:c7:43"
        dhcp: false
        addresses:
          - "192.168.0.20/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.0.1"
        mtu: 1500
        vip:
          ip: "192.168.0.10"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-labels.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"
