# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.0.10:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.0.10"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "talos-01"
    ipAddress: "192.168.0.20"
    installDiskSelector:
      serial: "S4EVNF0M454702F"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/249d9135de54962744e917cfe654117000cba369f9152fbab9d055a00aa3664f
    schematic:
      customization:
        extraKernelArgs:
          - i915.enable_guc=3 # Kaby Lake
        systemExtensions:
          officialExtensions:
            - siderolabs/i915
            - siderolabs/intel-ucode
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools
    controlPlane: true
    userVolumes:
      - name: local-hostpath
        provisioning:
          diskSelector:
            match: disk.serial == "S4J4NX0R819227P"
          maxSize: 2TB
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "54:b2:03:19:c7:43"
        dhcp: false
        addresses:
          - "192.168.0.20/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.0.1"
        mtu: 1500
        vip:
          ip: "192.168.0.10"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"
