---
originRequest:
  originServerName: "external.${SECRET_DOMAIN},external.${SECRET_DOMAIN_2}"

ingress:
  - hostname: "${SECRET_DOMAIN}"
    service: &svc https://cilium-gateway-external.kube-system.svc.cluster.local
  - hostname: "*.${SECRET_DOMAIN}"
    service: *svc
  - hostname: "${SECRET_DOMAIN_2}"
    service: &svc https://cilium-gateway-external.kube-system.svc.cluster.local
  - hostname: "*.${SECRET_DOMAIN_2}"
    service: *svc
  - service: http_status:404
