---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  chartRef:
    kind: OCIRepository
    name: longhorn
  interval: 1h
  values:
    defaultSettings:
      defaultReplicaCount: "1"
      defaultDataPath: /var/mnt/local-hostpath
      nodeDrainPolicy: allow-if-replica-is-stopped
    persistence:
      reclaimPolicy: Delete
      defaultClassReplicaCount: 1
    longhornUI:
      replicas: 1
    csi:
      attacherReplicaCount: 1
      provisionerReplicaCount: 1
      resizerReplicaCount: 1
      snapshotterReplicaCount: 1
    metrics:
      serviceMonitor:
        enabled: true