---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lssd-image-uploader
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      lssd-image-uploader:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/fatherosborn/discord-imgur-bot
              tag: main@sha256:7f752d167249e6ba34d5d788dd30313e4b29722871f4f8d8836dedcfe767e7f9
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 100Mi
    defaultPodOptions:
      imagePullSecrets:
        - name: ghcr-auth-secret
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534

