---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app smartctl-exporter
spec:
  chartRef:
    kind: OCIRepository
    name: smartctl-exporter
  interval: 1h
  values:
    fullnameOverride: *app
    prometheusRules:
      enabled: false
    serviceMonitor:
      enabled: true
      relabelings:
        - action: labeldrop
          regex: (pod)
