---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app snmp-exporter
spec:
  chartRef:
    kind: OCIRepository
    name: snmp-exporter
  interval: 1h
  values:
    fullnameOverride: *app
    serviceMonitor:
      enabled: true
      params:
        - name: nas
          auth: [public_v2]
          module: [if_mib, synology, ucd_la_table]
          target: nas.internal
      relabelings:
        - sourceLabels: [__param_target]
          targetLabel: instance
