---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: generic-device-plugin
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    defaultPodOptions:
      priorityClassName: system-node-critical
    controllers:
      generic-device-plugin:
        type: daemonset
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/squat/generic-device-plugin
              tag: latest@sha256:08ce98c7afed6843fc1e6082b1c414a00981bc8b90f3261c31b8efef8eca7c0e
            args:
              - --log-level=info
              - --config=/config/config.yaml
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 32Mi
            securityContext:
              # privileged: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    persistence:
      config:
        type: configMap
        name: generic-device-plugin
        globalMounts:
          - path: /config/config.yaml
            subPath: config.yaml
            readOnly: true
      dev:
        type: hostPath
        hostPath: /dev
        globalMounts:
          - readOnly: true
      sys:
        type: hostPath
        hostPath: /sys
        globalMounts:
          - readOnly: true
      var-lib-kubelet-device-plugins:
        type: hostPath
        hostPath: /var/lib/kubelet/device-plugins
