---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mining-cult
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      mining-cult:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/kwissss/mining-cult
              tag: main@sha256:a7b27c1e0c769fd4929c2b020f974b71608f483aa2fab4bba80a8c7d2479d7b8
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 5m
                memory: 15Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      imagePullSecrets:
        - name: ghcr-auth-secret
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: Always
    persistence:
      config:
        existingClaim: mining-cult
        advancedMounts:
          mining-cult:
            app:
              - path: /usr/src/app/auth-cache
                subPath: auth-cache/
              - path: /usr/src/app/config.json
                subPath: config.json
              - path: /usr/src/app/data
                subPath: data/
              - path: /usr/src/app/messages.json
                subPath: messages.json
              - path: /usr/src/app/node_modules/skyhelper-networth/.itemsBackup.json
                subPath: .itemsBackup.json
      cache:
        type: emptyDir
        globalMounts:
          - path: /usr/src/app/logs
            subPath: logs
