---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
resources:
  - ./cluster-secrets.sops.yaml
  - ./namespace.yaml
  - ./cloudflare-dns/ks.yaml
  - ./cloudflare-tunnel/ks.yaml
  - ./unifi-dns/ks.yaml
