apiVersion: v1
kind: ConfigMap
metadata:
  name: podinfo-helm-chart-value-overrides
  namespace: podinfo
data:
  values.yaml: |-
    replicaCount: 3
    ingress:
      enabled: true
      hosts:
        - host: podinfo.localtest.me
          paths:
            - path: /
              pathType: ImplementationSpecific
